spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpashop?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: sa
    password: km971gb5!!

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: false
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    defer-datasource-initialization: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: dailylifegit@gmail.com
    password: rhtzjhfmpfmvslvj

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
